#define EP_WP_TYPES \
	["MOVE", "DESTROY", "GETIN", "SAD", "JOIN", "LEADER", "GETOUT", "CYCLE", "LOAD", "UNLOAD", "TR UNLOAD", "HOLD", "SENTRY", \
	"GUARD", "TALK", "SCRIPTED", "SUPPORT", "GETIN NEAREST", "DISMISS", "LOITER", "HOOK", "UNHOOK"]

#define EP_BEHAVIOURS ["CARELESS", "SAFE", "AWARE", "COMBAT", "STEALTH"]
#define EP_FORMATIONS ["COLUMN", "STAG COLUMN", "WEDGE", "ECH LEFT", "ECH RIGHT", "VEE", "LINE", "FILE", "DIAMOND"]
#define EP_SPEED_MODES ["LIMITED", "NORMAL", "FULL", "UNCHANGED"]
#define EP_COMBAT_MODES ["BLUE", "GREEN", "WHITE", "YELLOW", "RED"]
#define EP_UNIT_POSITIONS ["AUTO", "DOWN", "MIDDLE", "UP"]

#define EP_TRIGGER_ACTIVATION_TYPES ["PRESENT", "NOT PRESENT", "WEST D", "EAST D", "GUER D", "CIV D"]
#define EP_TRIGGER_ACTIVATION_BY_SIDES ["EAST", "WEST", "GUER", "CIV", "LOGIC", "ANY", "ANYPLAYER"]
#define EP_TRIGGER_ACTIAVTION_BY_RADIO ["ALPHA", "BRAVO", "CHARLIE", "DELTA", "ECHO", "FOXTROT", "GOLD", "HOTEL", "INDIA", "JULIET"]
#define EP_TRIGGER_ACTIVATION_BY_OBJECT ["STATIC", "VEHICLE", "GROUP", "LEADER", "MEMBER"]
#define EP_TRIGGER_ACTIVATION_BY_STATUS ["WEST SEIZED", "EAST SEIZED", "GUER SEIZED"]


#define EP_SUBTITLES_SOUNDS_NOISES ["mynoise1", "mynoise2", "mynoise3"]
#define EP_SUBTITLES_SOUNDS_TYPING ["gm_rtty_stroke_01", "gm_rtty_stroke_02", "gm_rtty_stroke_03"]
#define EP_SUBTITLES_SOUNDS_TYPING_TIMINGS [0.06, 0.06, 0.06, 0.1, 0.3, 0.5]
#define EP_SUBTITLES_DEFAULT_SOUND_IN "myin1"
#define EP_SUBTITLES_DEFAULT_SOUND_OUT "myin4"